Issue#502
naver/arcus-memcached pull request #507
Opened 2020-09-04 09:56 UTC by dongwooklee96

do_item_replace () 함수를 최적화 하였습니다.

BEFORE:
```
do_item_unlink(old_it)
       
       - unlink from LRU list
       - assoc_delete
       - prefix unlink
       - update stats
do_item_link(new_it)
       - set cas
       - prefix link
       - assoc_insert
       - link to LRU list
       - update stats
```

AFTER 
```
- replace items from the LRU list when in the same class 
- assoc_delete
- assoc_insert
- prefix_replace
- update stats when it needs
```

2020-09-06 02:07 UTC, MinWooJin requested changes
1차 리뷰 완료 했습니다.
변경 사항이 반영되면 추가 리뷰 진행 하겠습니다.

2020-09-06 02:07 UTC, MinWooJin commented on engines/default/items.c
> +            CLOG_ITEM_LINK(new_it);
CLOG_ITEM_XXX macro는 item의 변경 로그를 기록하기 위한 macro로,
그 위치가 중요합니다. 로직상 기존과 같은 위치에 추가해두는편이 좋겠습니다.
(현재 위치는 new_it의 정보가 모두 세팅되지 않았는데, new_it으로 변경 로그를 기록하고 있습니다.)

2020-09-07 06:45 UTC, dongwooklee96 commented on engines/default/items.c
> +static ENGINE_ERROR_CODE do_item_replace(hash_item *old_it, hash_item *new_it)
이 부분은 제가 착각한 것 같습니다.  바꿔줄 필요가 없네요

2020-09-07 06:53 UTC, dongwooklee96 commented on engines/default/items.c
> +        assoc_delete(old_key, old_it->nkey, old_it->khash);
old_item과 new_item이 결국 같은 key로 동작할 수 밖에 없는 이유가 있나요?

2020-09-07 06:55 UTC, dongwooklee96 commented on engines/default/items.c
> +        if (old_it->slabs_clsid == new_it->slabs_clsid) {
CLOG_ITEM_UNLINK, LINK 호출 및 item_replace_q()는 제공하지 않는 부분으로 가겠습니다.

2020-09-07 07:11 UTC, dongwooklee96 commented on engines/default/items.c
> +            do_item_stat_unlink(old_it, old_stotal);
do_item_stat_replace() 함수를 만들어도 되나요?

2020-09-07 07:11 UTC, dongwooklee96 commented on engines/default/items.c
> +            CLOG_ITEM_LINK(new_it);
넵 알겠습니다

2020-09-07 07:14 UTC, MinWooJin commented on engines/default/items.c
> +        assoc_delete(old_key, old_it->nkey, old_it->khash);
old_item과 new_item의 key가 같기 때문에
assoc module에서 old_item의 위치를 찾아 제거하고 new_item이 추가될 위치를 찾아 추가하는 로직보단
assoc module에서 old_item의 위치를 찾고, new_item과 교체하면 최적화에 더 유리하다는 의미였습니다.

2020-09-08 06:03 UTC, jhpark816 commented
@dongwooklee96 @MinWooJin 
do_item_replace() 함수를 최적화하는 작업이 
기존 코드와 잘 맞게 수정해야 하기 때문에 어려움이 있을 것입니다.

아래의 최적화 방안으로 구현하면 좋을 것 같습니다.
- 먼저 new item에 대한 필요한 설정 수행
   - cas value with item_set_cas function
   - iflag (ITEM_INTERNAL 여부)
   - time, khash
- assoc_replace() 호출 (새로운 함수 추가 필요)
 - item_link_q()/unlink()는 그대로 호출
    - 최적화 효과보다 코드 복잡도가 증가한다고 보여서,
    - 이 부분은 기존 코드를 그대로 호출하는 것이 좋을 것 같습니다.
- prefix와 stat 부분에서 통계 정보 갱신
    - 이 부분은 아래에서 설명,
- 그리고, CLOG_ XXX 매크로는
   - replace 시작 시에 CLOG_ITEM_UNLINK() 호출
   - replace 마지막에 CLOG_ITEM_LINK() 호출

replace 시의 통계 정보 갱신은 아래 함수가 사용되는 곳을 참고하시고요.
```
static void do_coll_space_incr(coll_meta_info *info, ENGINE_ITEM_TYPE item_type,
                               const size_t nspace)
{
    info->stotal += nspace;

    hash_item *it = (hash_item*)COLL_GET_HASH_ITEM(info);
    do_item_stat_bytes_incr(it, nspace);
    prefix_bytes_incr(it->pfxptr, item_type, nspace);
}

static void do_coll_space_decr(coll_meta_info *info, ENGINE_ITEM_TYPE item_type,
                               const size_t nspace)
{
    assert(info->stotal >= nspace);
    info->stotal -= nspace;

    hash_item *it = (hash_item*)COLL_GET_HASH_ITEM(info);
    do_item_stat_bytes_decr(it, nspace);
    prefix_bytes_decr(it->pfxptr, item_type, nspace);
}
```

별도의 do_item_space_update() 함수를 두어 아래와 같이 구현한 후에
do_item_space_update() 함수를 호출하여 prefix와 stats 통계 정보를 한꺼번에 
갱신하면 될 것 같습니다.
- old_space == new_space
   - do nothing
- old_space < new_space
   - do_item_stat_bytes_incr(it, nspace); 호출
   - prefix_bytes_incr(it->pfxptr, item_type, nspace); 호출
- old_space > new_space
   - do_item_stat_bytes_decr(it, nspace); 호출
   - prefix_bytes_decr(it->pfxptr, item_type, nspace); 호축

2020-09-08 16:30 UTC, closed without merging